baseURL = "https://homelabaas.io/"
languageCode = "en-us"
title = "Homelab as a Service"
theme = "hugo-bootstrap"


[taxonomies]
  tag = "tags"
  category = "categories"

# Google analytics
googleAnalytics = "UA-16039647-5"

[languages.en]
  languageName = "English"

  # Replace the default footer message with a localized message
  # copyright = "Copyright Geoff Rich"

  [[languages.en.menu.main]]
    url = "/features/"
    name = "Features"
    weight = 1
  [[languages.en.menu.main]]
    url = "https://docs.homelabaas.io"
    name = "Docs"
    weight = 2
  [[languages.en.menu.main]]
    url = "https://github.com/homelabaas"
    name = "Github"
    weight = 3

# Links format

[permalinks]
  post = "/:year/:month/:title/"
